/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef PICTURE_PRIVATE_H
#define PICTURE_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.1.1.1"
#define VER_MAJOR	0
#define VER_MINOR	1
#define VER_RELEASE	1
#define VER_BUILD	1
#define COMPANY_NAME	""
#define FILE_VERSION	"1.0"
#define FILE_DESCRIPTION	""
#define INTERNAL_NAME	"Picture"
#define LEGAL_COPYRIGHT	"2012(c)Somov E. P."
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"Picture"
#define PRODUCT_VERSION	"1.0"

#endif /*PICTURE_PRIVATE_H*/
